package main // EVERY GO FILE NEEDS A PACKAGE. MAIN IS SPECIAL - IT'S THE ENTRY POINT

import "fmt" // BRINGS IN THE FORMATTING/PRINTING PACKAGE

func main() { // THE FUNCTION THAT RUNS WHEN YOU EXECUTE THE PROGRAM
   fmt.Println("Hello World") // PRINTS TEXT TO CONSOLE WITH A NEWLINE
}

// go build <filepath> : GENERATES AN EXECUTABLE FILE 
// ./helloworld.exe : RUNS THE EXECUTABLE

// SHORTCUT
// go run <filepath> : BUILDS AND RUN IN ONE GO